"""
This workflow is designed to:
1. Build documentation using Sphinx whenever there is a push to the docs/ directory or a manual workflow trigger.
2. Install all necessary dependencies (Sphinx and related extensions/themes.
3. Build the documentation and output it to the _build/ directory.
4. Automatically deploy the generated documentation to Github Pages, serving it from the gh-pages branch.
"""


name: Docs
on: 
  workflow_dispatch:
  push:
    paths:
      - docs/**
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          sudo apt-get install pandoc
          pip install sphinx sphinx_rtd_theme
          pip install sphinx_design
          pip install nbsphinx
          pip install pydata-sphinx-theme
          pip install -r requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
